changelog:
  categories:
    - title: "Breaking Changes"
      labels:
        - "breaking"
    - title: "Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "Documentation"
      labels:
        - "docs"
    - title: "Chores"
      labels:
        - "chore"
        - "deps"
    - title: "Other Changes"
      labels:
        - "*"
